import { BlogPost, TeamMember, ProjectSettings, ForecastScenario, FlowFeature, MitreStageInfo, StorageTier, TechItem, ComparisonMetric } from '../types';

import yashminiPhoto from '../assets/images/leader_yashmini_1790055834771.jpg';
import sivaharishPhoto from '../assets/images/member_sivaharish_1790055850844.jpg';
import dharanishPhoto from '../assets/images/member_dharanish_1790055865669.jpg';
import vishnuPhoto from '../assets/images/member_vishnu_1790055878637.jpg';
import naviyaSriPhoto from '../assets/images/member_naviyasri_1790055891516.jpg';
import yawanthikaPhoto from '../assets/images/member_yawanthika_1790055904933.jpg';

export const DEFAULT_PROJECT_SETTINGS: ProjectSettings = {
  projectName: "AI-Based Network Attack Forecasting",
  projectSubtitle: "Predicting possible future attack progression from network traffic behaviour using AI.",
  teamName: "Team CyberForecast",
  primaryTagline: "Understand What Happens Next.",
  secondaryTagline: "Observe → Learn → Predict → Explain → Protect",
  demoDisclaimer: "Demonstration Data — Simulated network risk projections generated by prototype World Model inference.",
  storageRetentionDays: 30,
  systemStatus: "ONLINE",
  contactEmail: "sivaharish885@gmail.com",
  governanceLead: "Sivaharish R",
  adminPasskey: "cyberforecast2025",
  hideAdminFromPublic: true
};

export const CATEGORIES = [
  "All",
  "Cybersecurity",
  "AI & ML",
  "Digital Forensics",
  "Threat Intelligence",
  "Network Analysis",
  "Predictive Modeling",
  "MITRE ATT&CK",
  "Explainable AI",
  "Incident Response",
  "Zero Trust"
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "tm-1",
    name: "Yashmini N. P",
    role: "Team Leader",
    isLeader: true,
    avatar: "/team/yashmini.jpg",
    bio: "Guiding the research agenda, multi-disciplinary technical coordination, presentation design, and overall architecture planning for proactive network attack forecasting.",
    skills: ["Project Leadership", "System Coordination", "Cyber Strategy", "Presentation", "Technical Planning"],
    contributions: [
      "Directed end-to-end hackathon project lifecycle and deliverable milestones",
      "Formulated system narrative: Observe → Learn → Predict → Explain → Protect",
      "Synthesized research validation metrics and stakeholder presentations",
      "Managed cross-functional integration between AI modeling and network parsing"
    ],
    linkedin: "https://www.linkedin.com",
    email: "yashmini@cyberforecast.ai",
    order: 1
  },
  {
    id: "tm-2",
    name: "Sivaharish R",
    role: "AI & World Model Architect",
    isLeader: false,
    avatar: "/team/sivaharish.jpg",
    bio: "Focuses on deep learning architectures, sequence-to-sequence transitions, LSTM / Transformer World Models, and future network attack trajectory probability forecasting.",
    skills: ["PyTorch", "LSTM / Transformer", "World Models", "Sequence Prediction", "Scikit-Learn"],
    contributions: [
      "Architected the P(S_{t+1} | S_t) sequence progression model for multi-horizon forecasting",
      "Trained autoregressive recurrent networks on CICIDS2017 & UNSW-NB15 attack flows",
      "Implemented calibrated confidence estimators for K-step risk probability curves",
      "Benchmarked inference latency for sub-50ms air-gapped local execution"
    ],
    linkedin: "https://www.linkedin.com",
    email: "sivaharish885@gmail.com",
    order: 2
  },
  {
    id: "tm-3",
    name: "Dharanish C. B",
    role: "Network Traffic & PCAP Pipeline Engineer",
    isLeader: false,
    avatar: "/team/dharanish.jpg",
    bio: "Specializes in high-speed packet ingestion, Scapy / libpcap stream reassembly, bidirectional flow extraction, and 15+ statistical feature engineering algorithms.",
    skills: ["Scapy", "PCAP Forensics", "Flow Reassembly", "Wireshark", "Feature Engineering"],
    contributions: [
      "Engineered real-time sliding window parser for 15+ bidirectional flow statistics",
      "Designed zero-loss PCAP batch ingester with packet inter-arrival time (IAT) calculations",
      "Built packet flag ratio extractors (SYN, ACK, RST, FIN, PSH) under high throughput",
      "Optimized flow key hashing (5-tuple: src/dst IP, src/dst port, protocol)"
    ],
    linkedin: "https://www.linkedin.com",
    email: "dharanish@cyberforecast.ai",
    order: 3
  },
  {
    id: "tm-4",
    name: "Vishnu S",
    role: "Full-Stack & Real-Time Dashboard Engineer",
    isLeader: false,
    avatar: "/team/vishnu.jpg",
    bio: "Constructs responsive, high-performance cybersecurity dashboards, reactive streaming visualization, interactive risk plots, and local SQLite data tiers.",
    skills: ["React & TypeScript", "Tailwind CSS", "Chart.js & Canvas", "SQLite", "API Design"],
    contributions: [
      "Developed interactive 5-step forecast timeline with dynamic scenario switcher",
      "Created 3-tier local storage visualization and 24-hr forensic report generator",
      "Implemented responsive Slate Dark Cyber aesthetic with WCAG AA compliance",
      "Engineered client-side state synchronization with robust local persistence"
    ],
    linkedin: "https://www.linkedin.com",
    email: "vishnu@cyberforecast.ai",
    order: 4
  },
  {
    id: "tm-5",
    name: "Naviya Sri I",
    role: "XAI & MITRE ATT&CK Specialist",
    isLeader: false,
    avatar: "/team/naviyasri.jpg",
    bio: "Dedicates research to Explainable AI (SHAP, Integrated Gradients), translating neural attention weights into human-understandable MITRE tactic trajectories.",
    skills: ["SHAP Values", "Explainable AI (XAI)", "MITRE ATT&CK", "Attention Attribution", "Threat Mapping"],
    contributions: [
      "Built feature attribution pipeline mapping SHAP values to flow anomaly drivers",
      "Mapped forecasted state vectors to MITRE Enterprise tactics (TA0043 to TA0010)",
      "Formulated Human-in-the-Loop decision matrix with contextual SOC playbooks",
      "Eliminated black-box skepticism for security operations tier-2 analysts"
    ],
    linkedin: "https://www.linkedin.com",
    email: "naviyasri@cyberforecast.ai",
    order: 5
  },
  {
    id: "tm-6",
    name: "Yawanthika N",
    role: "Threat Intelligence & Security Evaluator",
    isLeader: false,
    avatar: "/team/yawanthika.jpg",
    bio: "Analyzes adversary TTPs, curates simulated cyberattack datasets, validates false positive mitigation, and executes system security evaluations.",
    skills: ["Threat Intelligence", "Adversary TTPs", "Model Evaluation", "Incident Response", "Forensic Auditing"],
    contributions: [
      "Generated multi-stage attack scenarios (Recon → Exploit → Lateral → Exfil)",
      "Conducted false positive stress testing across bursty corporate traffic profiles",
      "Designed Risk-Adaptive Evidence Capture threshold logic (92% storage savings)",
      "Authored operational runbooks and comprehensive technical research articles"
    ],
    linkedin: "https://www.linkedin.com",
    email: "yawanthika@cyberforecast.ai",
    order: 6
  }
];

export const FLOW_FEATURES: FlowFeature[] = [
  {
    name: "Flow Duration",
    key: "flow_duration_ms",
    sampleValue: "412.8 ms",
    unit: "Milliseconds",
    category: "Temporal",
    description: "Total elapsed time between the first and last packet observed for a given 5-tuple flow.",
    importanceRank: 4
  },
  {
    name: "SYN Flag Ratio",
    key: "syn_flag_ratio",
    sampleValue: "0.84",
    unit: "Ratio (0.0 - 1.0)",
    category: "Flag",
    description: "Proportion of packets carrying the SYN flag without corresponding ACKs; primary marker for port scanning or SYN flood.",
    importanceRank: 1
  },
  {
    name: "Mean Inter-Arrival Time",
    key: "mean_iat_us",
    sampleValue: "18.4 µs",
    unit: "Microseconds",
    category: "Temporal",
    description: "Average interval between consecutive packets. Unusually small or perfectly periodic intervals indicate automated tool activity.",
    importanceRank: 2
  },
  {
    name: "RST Flag Ratio",
    key: "rst_flag_ratio",
    sampleValue: "0.42",
    unit: "Ratio (0.0 - 1.0)",
    category: "Flag",
    description: "Fraction of flows abruptly terminated by RST packets, frequent during horizontal port scanning against closed targets.",
    importanceRank: 5
  },
  {
    name: "Target Port Diversity",
    key: "unique_dst_ports",
    sampleValue: "148 ports/sec",
    unit: "Count",
    category: "Volumetric",
    description: "Number of distinct destination ports touched within a rolling 5-second observation window.",
    importanceRank: 3
  },
  {
    name: "TTL Variance",
    key: "ttl_variance",
    sampleValue: "14.2",
    unit: "Std Dev",
    category: "Statistical",
    description: "Fluctuation in Time-To-Live values, indicating multi-path spoofing or botnet proxy routing.",
    importanceRank: 6
  },
  {
    name: "Packet Length Skew",
    key: "pkt_len_skew",
    sampleValue: "2.89",
    unit: "Coefficient",
    category: "Statistical",
    description: "Skewness of packet size distribution; anomalous small packets reflect handshakes while uniform payloads suggest exfiltration.",
    importanceRank: 7
  },
  {
    name: "Down / Up Byte Ratio",
    key: "down_up_byte_ratio",
    sampleValue: "0.08",
    unit: "Ratio",
    category: "Volumetric",
    description: "Ratio of inbound to outbound bytes. Skewed outbound traffic indicates potential data exfiltration or beaconing.",
    importanceRank: 8
  },
  {
    name: "Flow Packets / Sec",
    key: "flow_pkts_per_sec",
    sampleValue: "3,840 pkts/s",
    unit: "Rate",
    category: "Volumetric",
    description: "Volumetric packet throughput within the flow window. Key telemetry for exhaustion detection.",
    importanceRank: 9
  },
  {
    name: "ACK Packet Count",
    key: "ack_count",
    sampleValue: "12",
    unit: "Count",
    category: "Flag",
    description: "Total acknowledgments observed. Severe disparity between SYN and ACK reveals half-open TCP attacks.",
    importanceRank: 10
  }
];

export const FORECAST_SCENARIOS: ForecastScenario[] = [
  {
    id: "sc-1",
    name: "Stealth Reconnaissance → Brute Force Escalation",
    threatType: "Multi-Stage Credential Attack",
    description: "Initial low-frequency SYN scanning across subnet 192.168.1.0/24 transitions into credential stuffing against SSH port 22 and RDP port 3389.",
    severity: "HIGH",
    attackVector: "TCP SYN Sweep followed by Hydra/Medusa credential exhaustion",
    steps: [
      {
        step: "T+1 (+10s)",
        stepIndex: 1,
        horizonSeconds: 10,
        riskScore: 0.38,
        predictedStage: "Active Service Fingerprinting",
        mitreTactic: "Reconnaissance",
        techniqueId: "T1046",
        confidence: 0.94,
        topFeatures: [
          { feature: "SYN Flag Ratio", impact: "positive", shapValue: +0.32 },
          { feature: "Target Port Diversity", impact: "positive", shapValue: +0.28 },
          { feature: "Mean IAT", impact: "negative", shapValue: -0.09 }
        ],
        recommendedAction: "Apply temporary rate-limiting on gateway edge router for source IP subnet."
      },
      {
        step: "T+2 (+30s)",
        stepIndex: 2,
        horizonSeconds: 30,
        riskScore: 0.54,
        predictedStage: "Vulnerability Scanning",
        mitreTactic: "Initial Access",
        techniqueId: "T1190",
        confidence: 0.89,
        topFeatures: [
          { feature: "Unique Dst Ports", impact: "positive", shapValue: +0.41 },
          { feature: "RST Flag Ratio", impact: "positive", shapValue: +0.33 },
          { feature: "Packet Length Skew", impact: "positive", shapValue: +0.12 }
        ],
        recommendedAction: "Pre-emptively trigger Risk-Adaptive PCAP Capture (Level 1 Buffer retention)."
      },
      {
        step: "T+3 (+60s)",
        stepIndex: 3,
        horizonSeconds: 60,
        riskScore: 0.72,
        predictedStage: "SSH/RDP Brute Force Attempt",
        mitreTactic: "Credential Access",
        techniqueId: "T1110",
        confidence: 0.86,
        topFeatures: [
          { feature: "Flow Packets/s", impact: "positive", shapValue: +0.48 },
          { feature: "Mean IAT Anomaly", impact: "positive", shapValue: +0.39 },
          { feature: "ACK Disparity", impact: "positive", shapValue: +0.22 }
        ],
        recommendedAction: "Activate IP quarantine rule on firewall; enforce MFA challenge on PAM layer."
      },
      {
        step: "T+4 (+120s)",
        stepIndex: 4,
        horizonSeconds: 120,
        riskScore: 0.88,
        predictedStage: "Privileged Session Acquisition",
        mitreTactic: "Execution",
        techniqueId: "T1059",
        confidence: 0.81,
        topFeatures: [
          { feature: "Down/Up Byte Ratio", impact: "positive", shapValue: +0.55 },
          { feature: "Flow Duration", impact: "positive", shapValue: +0.37 },
          { feature: "TTL Variance", impact: "positive", shapValue: +0.21 }
        ],
        recommendedAction: "Isolate target VM into forensic VLAN; dump host memory for volatile forensics."
      },
      {
        step: "T+5 (+300s)",
        stepIndex: 5,
        horizonSeconds: 300,
        riskScore: 0.94,
        predictedStage: "Internal Subnet Pivoting",
        mitreTactic: "Lateral Movement",
        techniqueId: "T1021",
        confidence: 0.78,
        topFeatures: [
          { feature: "Internal Peer Connections", impact: "positive", shapValue: +0.62 },
          { feature: "SYN Flag Volume", impact: "positive", shapValue: +0.44 },
          { feature: "Byte Skewness", impact: "positive", shapValue: +0.31 }
        ],
        recommendedAction: "Emergency network segmentation lockdown; revoke active Kerberos TGT tickets."
      }
    ]
  },
  {
    id: "sc-2",
    name: "Cobalt Strike C2 Beaconing → Lateral Movement",
    threatType: "Advanced Persistent Threat (APT)",
    description: "Periodic low-entropy jittered HTTP/DNS beaconing establishing command-and-control, followed by WMI/SMB lateral traversal.",
    severity: "CRITICAL",
    attackVector: "Malleable C2 Beacon with 60s sleep + 20% jitter moving to SMB Named Pipes",
    steps: [
      {
        step: "T+1 (+10s)",
        stepIndex: 1,
        horizonSeconds: 10,
        riskScore: 0.45,
        predictedStage: "C2 Keep-Alive Handshake",
        mitreTactic: "Command and Control",
        techniqueId: "T1071",
        confidence: 0.91,
        topFeatures: [
          { feature: "Mean IAT Jitter", impact: "positive", shapValue: +0.42 },
          { feature: "Down/Up Byte Ratio", impact: "positive", shapValue: +0.31 },
          { feature: "SYN Flag Ratio", impact: "negative", shapValue: -0.15 }
        ],
        recommendedAction: "Inspect outbound proxy logs for unclassified domain reputations."
      },
      {
        step: "T+2 (+30s)",
        stepIndex: 2,
        horizonSeconds: 30,
        riskScore: 0.62,
        predictedStage: "Payload Staging & Download",
        mitreTactic: "Execution",
        techniqueId: "T1105",
        confidence: 0.88,
        topFeatures: [
          { feature: "Inbound Flow Bytes", impact: "positive", shapValue: +0.51 },
          { feature: "Packet Length Variance", impact: "positive", shapValue: +0.38 },
          { feature: "Mean IAT", impact: "positive", shapValue: +0.22 }
        ],
        recommendedAction: "Block external egress IP on core gateway; trigger endpoint EDR inspection."
      },
      {
        step: "T+3 (+60s)",
        stepIndex: 3,
        horizonSeconds: 60,
        riskScore: 0.79,
        predictedStage: "Domain Reconnaissance via LDAP/RPC",
        mitreTactic: "Discovery",
        techniqueId: "T1087",
        confidence: 0.84,
        topFeatures: [
          { feature: "Port 389/445 Query Count", impact: "positive", shapValue: +0.58 },
          { feature: "Unique Internal Dst IPs", impact: "positive", shapValue: +0.44 },
          { feature: "ACK Disparity", impact: "positive", shapValue: +0.19 }
        ],
        recommendedAction: "Restrict domain controller RPC access to authenticated IT management subnets only."
      },
      {
        step: "T+4 (+120s)",
        stepIndex: 4,
        horizonSeconds: 120,
        riskScore: 0.91,
        predictedStage: "Lateral Movement via SMB Exec",
        mitreTactic: "Lateral Movement",
        techniqueId: "T1021.002",
        confidence: 0.82,
        topFeatures: [
          { feature: "SMB Pipe Write Volume", impact: "positive", shapValue: +0.64 },
          { feature: "Flow Duration Anomaly", impact: "positive", shapValue: +0.41 },
          { feature: "RST Flag Ratio", impact: "negative", shapValue: -0.11 }
        ],
        recommendedAction: "Block SMB TCP port 445 cross-subnet routing; sever infected host sessions."
      },
      {
        step: "T+5 (+300s)",
        stepIndex: 5,
        horizonSeconds: 300,
        riskScore: 0.97,
        predictedStage: "Automated Data Exfiltration",
        mitreTactic: "Exfiltration",
        techniqueId: "T1048",
        confidence: 0.79,
        topFeatures: [
          { feature: "Outbound Byte Velocity", impact: "positive", shapValue: +0.72 },
          { feature: "Down/Up Ratio Collapse", impact: "positive", shapValue: +0.53 },
          { feature: "TTL Variance", impact: "positive", shapValue: +0.28 }
        ],
        recommendedAction: "Immediate enterprise gateway egress sinkholing; initiate incident breach response."
      }
    ]
  },
  {
    id: "sc-3",
    name: "Volumetric SYN Flood / Network Service Exhaustion",
    threatType: "Denial of Service (DoS)",
    description: "Rapidly escalating half-open TCP SYN packet surge overwhelming state tables of perimeter web application firewalls.",
    severity: "CRITICAL",
    attackVector: "Distributed SYN Flood with IP Spoofing and pseudo-random source ports",
    steps: [
      {
        step: "T+1 (+10s)",
        stepIndex: 1,
        horizonSeconds: 10,
        riskScore: 0.52,
        predictedStage: "SYN Rate Spike Detection",
        mitreTactic: "Impact",
        techniqueId: "T1498",
        confidence: 0.95,
        topFeatures: [
          { feature: "SYN Flag Ratio", impact: "positive", shapValue: +0.62 },
          { feature: "Flow Packets/s", impact: "positive", shapValue: +0.48 },
          { feature: "ACK Disparity", impact: "positive", shapValue: +0.35 }
        ],
        recommendedAction: "Enable SYN cookies on perimeter Linux kernel sysctl; adjust backlog queue."
      },
      {
        step: "T+2 (+30s)",
        stepIndex: 2,
        horizonSeconds: 30,
        riskScore: 0.74,
        predictedStage: "Connection Table Saturation",
        mitreTactic: "Impact",
        techniqueId: "T1499",
        confidence: 0.92,
        topFeatures: [
          { feature: "Half-Open Flow Count", impact: "positive", shapValue: +0.68 },
          { feature: "Mean IAT Collapse", impact: "positive", shapValue: +0.51 },
          { feature: "TTL Variance", impact: "positive", shapValue: +0.24 }
        ],
        recommendedAction: "Engage upstream ISP BGP Flowspec rate limits; drop unverified spoofed prefixes."
      },
      {
        step: "T+3 (+60s)",
        stepIndex: 3,
        horizonSeconds: 60,
        riskScore: 0.89,
        predictedStage: "Target Service Response Degradation",
        mitreTactic: "Impact",
        techniqueId: "T1499.001",
        confidence: 0.89,
        topFeatures: [
          { feature: "RST/Timeout Ratio", impact: "positive", shapValue: +0.71 },
          { feature: "Flow Packets/s", impact: "positive", shapValue: +0.56 },
          { feature: "Packet Length Skew", impact: "positive", shapValue: +0.31 }
        ],
        recommendedAction: "Divert ingress HTTP/HTTPS traffic through cloud DDoS scrubbing proxy."
      },
      {
        step: "T+4 (+120s)",
        stepIndex: 4,
        horizonSeconds: 120,
        riskScore: 0.96,
        predictedStage: "Full Gateway Port Exhaustion",
        mitreTactic: "Impact",
        techniqueId: "T1498.001",
        confidence: 0.85,
        topFeatures: [
          { feature: "Socket Buffer Drops", impact: "positive", shapValue: +0.77 },
          { feature: "SYN Flag Ratio", impact: "positive", shapValue: +0.65 },
          { feature: "Unique Src IPs", impact: "positive", shapValue: +0.49 }
        ],
        recommendedAction: "Failover critical services to secondary isolated IP block; blackhole target VIP."
      },
      {
        step: "T+5 (+300s)",
        stepIndex: 5,
        horizonSeconds: 300,
        riskScore: 0.99,
        predictedStage: "Cascading Service Failure",
        mitreTactic: "Impact",
        techniqueId: "T1498",
        confidence: 0.82,
        topFeatures: [
          { feature: "Total Bandwidth Saturation", impact: "positive", shapValue: +0.81 },
          { feature: "DNS Resolution Timeouts", impact: "positive", shapValue: +0.58 },
          { feature: "Drop Rate %", impact: "positive", shapValue: +0.44 }
        ],
        recommendedAction: "Execute disaster recovery business continuity runbook."
      }
    ]
  },
  {
    id: "sc-4",
    name: "Benign Corporate Workflow Baseline",
    threatType: "Normal Traffic Profile",
    description: "Standard employee browsing, scheduled database synchronization, and encrypted SaaS microservices with healthy bidirectional flow balance.",
    severity: "LOW",
    attackVector: "Legitimate HTTPS, SSH maintenance, and DNS queries",
    steps: [
      {
        step: "T+1 (+10s)",
        stepIndex: 1,
        horizonSeconds: 10,
        riskScore: 0.08,
        predictedStage: "Normal HTTP/S Transactions",
        mitreTactic: "Benign Activity",
        techniqueId: "NONE",
        confidence: 0.98,
        topFeatures: [
          { feature: "SYN Flag Ratio", impact: "negative", shapValue: -0.45 },
          { feature: "Balanced Down/Up Ratio", impact: "negative", shapValue: -0.38 },
          { feature: "Normal IAT Dispersion", impact: "negative", shapValue: -0.29 }
        ],
        recommendedAction: "Continue regular Level 2 compact feature logging; maintain passive monitoring."
      },
      {
        step: "T+2 (+30s)",
        stepIndex: 2,
        horizonSeconds: 30,
        riskScore: 0.09,
        predictedStage: "Standard TLS Sessions",
        mitreTactic: "Benign Activity",
        techniqueId: "NONE",
        confidence: 0.97,
        topFeatures: [
          { feature: "Valid Handshakes", impact: "negative", shapValue: -0.48 },
          { feature: "TTL Consistency", impact: "negative", shapValue: -0.33 },
          { feature: "Low RST Rate", impact: "negative", shapValue: -0.27 }
        ],
        recommendedAction: "No operational intervention required."
      },
      {
        step: "T+3 (+60s)",
        stepIndex: 3,
        horizonSeconds: 60,
        riskScore: 0.11,
        predictedStage: "Scheduled Backup Sync",
        mitreTactic: "Benign Activity",
        techniqueId: "NONE",
        confidence: 0.95,
        topFeatures: [
          { feature: "Expected Destination CIDR", impact: "negative", shapValue: -0.52 },
          { feature: "Stable Flow Duration", impact: "negative", shapValue: -0.31 },
          { feature: "Packet Skew Normal", impact: "negative", shapValue: -0.19 }
        ],
        recommendedAction: "No action needed; known scheduled cloud synchronization."
      },
      {
        step: "T+4 (+120s)",
        stepIndex: 4,
        horizonSeconds: 120,
        riskScore: 0.12,
        predictedStage: "Idle Flow Pruning",
        mitreTactic: "Benign Activity",
        techniqueId: "NONE",
        confidence: 0.94,
        topFeatures: [
          { feature: "Graceful FIN Closures", impact: "negative", shapValue: -0.49 },
          { feature: "Zero Port Anomalies", impact: "negative", shapValue: -0.36 },
          { feature: "Benign Host Reputation", impact: "negative", shapValue: -0.25 }
        ],
        recommendedAction: "Standard session garbage collection in Level 1 ring buffer."
      },
      {
        step: "T+5 (+300s)",
        stepIndex: 5,
        horizonSeconds: 300,
        riskScore: 0.10,
        predictedStage: "Steady State Baseline",
        mitreTactic: "Benign Activity",
        techniqueId: "NONE",
        confidence: 0.96,
        topFeatures: [
          { feature: "Low Entropy Distribution", impact: "negative", shapValue: -0.55 },
          { feature: "Balanced Flags", impact: "negative", shapValue: -0.42 },
          { feature: "Nominal Jitter", impact: "negative", shapValue: -0.30 }
        ],
        recommendedAction: "System nominal; write scheduled 24-hr status roll-up summary."
      }
    ]
  }
];

export const MITRE_STAGES: MitreStageInfo[] = [
  {
    id: "recon",
    stageName: "Reconnaissance",
    mitreTactic: "TA0043 Reconnaissance",
    tacticId: "TA0043",
    techniqueId: "T1046",
    techniqueName: "Network Service Discovery",
    description: "Adversaries probe victim IP space to catalogue active hosts, open listening ports, and daemon software versions.",
    detectionIndicators: ["High SYN ratio with zero payload", "Rapid destination port incrementation", "Excessive ICMP echo sweeps"],
    recommendedPlaybook: "Rate-limit border router ingress; dynamically blackhole high-frequency probe origins; alert SOC tier-1.",
    urgency: "Low"
  },
  {
    id: "initial-access",
    stageName: "Initial Access",
    mitreTactic: "TA0001 Initial Access",
    tacticId: "TA0001",
    techniqueId: "T1190",
    techniqueName: "Exploit Public-Facing Application",
    description: "Attacker targets unpatched vulnerabilities or misconfigurations on DMZ edge servers (e.g. Log4j, OpenSSH, VPN gateways).",
    detectionIndicators: ["Malformed HTTP URI queries", "Unusual POST payload volume", "Segmentation fault core dumps"],
    recommendedPlaybook: "Engage WAF virtual patching; isolate perimeter reverse proxy container; review gateway session state.",
    urgency: "Moderate"
  },
  {
    id: "execution",
    stageName: "Execution",
    mitreTactic: "TA0002 Execution",
    tacticId: "TA0002",
    techniqueId: "T1059",
    techniqueName: "Command and Scripting Interpreter",
    description: "Malicious shell scripts, PowerShell commands, or native OS binaries are spawned on the compromised host.",
    detectionIndicators: ["Unusual bash/sh process spawned by web daemon", "Outbound DNS requests with Base64 subdomains", "Base64 encoded execution strings"],
    recommendedPlaybook: "Execute endpoint process freeze; terminate parent shell PID; preserve memory image for volatility audit.",
    urgency: "High"
  },
  {
    id: "lateral-movement",
    stageName: "Lateral Movement",
    mitreTactic: "TA0008 Lateral Movement",
    tacticId: "TA0008",
    techniqueId: "T1021",
    techniqueName: "Remote Services (SMB / RDP / SSH)",
    description: "Adversaries pivot across the internal network using compromised credentials or protocol vulnerabilities to reach high-value assets.",
    detectionIndicators: ["Sudden internal traffic on ports 445, 135, or 3389", "Abnormal service account logons", "Pass-the-Hash token reuse"],
    recommendedPlaybook: "Sever east-west microsegmentation routes; invalidate domain admin Kerberos tokens; quarantine source workstation.",
    urgency: "Immediate"
  },
  {
    id: "command-control",
    stageName: "Command & Control",
    mitreTactic: "TA0011 Command and Control",
    tacticId: "TA0011",
    techniqueId: "T1071",
    techniqueName: "Application Layer Protocol (Beaconing)",
    description: "Compromised internal host communicates stealthily with attacker-controlled infrastructure via jittered HTTP, TLS, or DNS tunnels.",
    detectionIndicators: ["Consistent packet inter-arrival time with artificial jitter", "Low byte counts with high frequency", "DGA domain queries"],
    recommendedPlaybook: "Sinkhole destination C2 FQDN at local DNS resolvers; drop outbound traffic on border firewall; alert incident commander.",
    urgency: "Immediate"
  },
  {
    id: "exfiltration",
    stageName: "Exfiltration",
    mitreTactic: "TA0010 Exfiltration",
    tacticId: "TA0010",
    techniqueId: "T1048",
    techniqueName: "Exfiltration Over Alternative Protocol",
    description: "Sensitive corporate data, database dumps, or intellectual property are transferred out to external drop-points.",
    detectionIndicators: ["Severe asymmetry in Down/Up byte ratio (massive outbound)", "Encrypted archive uploads over non-standard ports", "DNS TXT record tunneling"],
    recommendedPlaybook: "Instantly throttle or sever external WAN uplink for target host; preserve full PCAP Level 1 buffer; commence regulatory breach protocol.",
    urgency: "Immediate"
  }
];

export const STORAGE_TIERS: StorageTier[] = [
  {
    level: 1,
    name: "Temporary Packet Ring Buffer",
    technology: "In-Memory Circular Buffer + Fast NVMe FIFO",
    latency: "< 0.5 ms",
    retention: "15 to 60 Minutes (Rolling)",
    capacityImpact: "High raw bandwidth (10-20 GB/hr), automatically pruned",
    description: "Captures full raw packet headers and initial payload bytes. When the World Model predicts risk R > 0.65, the buffer freezes evidence to persistent disk.",
    features: [
      "Zero-copy packet ring via AF_PACKET / DPDK hooks",
      "Dynamic freeze trigger on predicted risk threshold",
      "Automatic circular overwrite during benign baselines",
      "Guarantees forensic evidence without multi-terabyte overhead"
    ]
  },
  {
    level: 2,
    name: "Compact Feature Vector DB",
    technology: "SQLite / Embedded Parquet Columnar Store",
    latency: "2 - 10 ms",
    retention: "7 to 30 Days",
    capacityImpact: "95% smaller than raw PCAP (~150 MB/day for 1M flows)",
    description: "Stores aggregated 15+ flow statistics (duration, IAT, flag ratios, byte distributions) per 5-tuple window for trend forecasting and retraining.",
    features: [
      "Compressed schema optimized for fast time-series aggregation",
      "Supports instant SQL queries for historical attack replay",
      "Feeds SHAP explainability and attention weight visualizers",
      "Low disk footprint suitable for edge industrial gateways"
    ]
  },
  {
    level: 3,
    name: "24-Hour Forensic & Executive Reports",
    technology: "Encrypted JSON / HTML / Signed PDF Artifacts",
    latency: "Batch generated daily",
    retention: "90 Days to 1 Year (Auditable)",
    capacityImpact: "Extremely compact (< 5 MB/day)",
    description: "Synthesizes daily threat forecasts, actual observed trajectory confirmations, top MITRE techniques, and analyst response audits.",
    features: [
      "Human-readable SOC executive summary + machine-parsable JSON",
      "Cryptographically signed SHA-256 hash for legal chain of custody",
      "Automated compliance documentation (NIST, ISO 27001)",
      "Zero-cloud dependencies: generated entirely offline"
    ]
  }
];

export const TECH_STACK: TechItem[] = [
  {
    name: "Python 3.11",
    category: "Capture & Ingestion",
    role: "Core Execution Runtime",
    description: "High-performance base environment executing asynchronous packet ingestion workers, model inference loops, and mathematical vector processing.",
    badge: "Runtime"
  },
  {
    name: "Scapy & libpcap",
    category: "Capture & Ingestion",
    role: "Packet Dissection & Flow Reassembly",
    description: "Low-level network packet sniffing, protocol decoding, 5-tuple session tracking, and PCAP file parsing with microsecond precision.",
    badge: "Ingestion"
  },
  {
    name: "Pandas & NumPy",
    category: "ML & AI Core",
    role: "Vectorized Feature Engineering",
    description: "Calculates rolling statistical windows, inter-arrival time distributions, variance, skewness, and flag ratios at high throughput.",
    badge: "Data Science"
  },
  {
    name: "PyTorch",
    category: "ML & AI Core",
    role: "Deep Learning & World Model Core",
    description: "Powers the sequence-to-sequence neural architecture modeling P(S_{t+1} | S_t) with bidirectional recurrent units and self-attention.",
    badge: "Neural Nets"
  },
  {
    name: "LSTM & Transformer",
    category: "ML & AI Core",
    role: "Temporal State Transition Engine",
    description: "Learns multi-step temporal dependencies across attack stages, enabling forecasting of future states across T+1 to T+5 time horizons.",
    badge: "Forecasting"
  },
  {
    name: "Scikit-learn",
    category: "ML & AI Core",
    role: "Baseline Models & Calibration",
    description: "Provides standard anomaly detection baselines (Isolation Forest, One-Class SVM) and probability calibration tools.",
    badge: "Validation"
  },
  {
    name: "SHAP (SHapley Additive exPlanations)",
    category: "Forecasting & XAI",
    role: "Explainable AI (XAI) Attribution",
    description: "Deconstructs black-box model decisions into quantitative feature importance weights, showing exactly why a forecast risk was assigned.",
    badge: "Explainability"
  },
  {
    name: "MITRE ATT&CK Framework",
    category: "Forecasting & XAI",
    role: "Adversary TTP Taxonomy",
    description: "Standardized taxonomy mapping forecasted future network states directly to recognized adversary tactics, techniques, and procedures.",
    badge: "Threat Intel"
  },
  {
    name: "SQLite & Parquet",
    category: "Storage & Viz",
    role: "Compact Embedded Data Tier",
    description: "Lightweight, zero-maintenance local database engine storing flow vectors and historical forecasts with zero external database servers.",
    badge: "Storage"
  },
  {
    name: "Chart.js & Canvas",
    category: "Storage & Viz",
    role: "Dynamic Risk & Trajectory Plots",
    description: "Renders interactive multi-step risk probability curves, SHAP contribution bars, and live traffic volume visualizers with zero latency.",
    badge: "Visualization"
  },
  {
    name: "Tailwind CSS & React",
    category: "Storage & Viz",
    role: "Modern Cyber UI Platform",
    description: "Provides sleek Slate Dark Cyber aesthetics, responsive layout, accessible typography, and smooth interaction states for SOC analysts.",
    badge: "Frontend"
  }
];

export const COMPARISON_METRICS: ComparisonMetric[] = [
  {
    feature: "Core Question Answered",
    traditionalIds: "\"Is an attack happening right now?\" (Reactive Detection)",
    proposedSystem: "\"What is likely to happen next, and when?\" (Proactive Forecasting)",
    advantage: "Provides defenders a 30s to 5-minute pre-emptive response window before damage occurs."
  },
  {
    feature: "Detection Paradigm",
    traditionalIds: "Signature matching (Snort/Suricata) or point-in-time threshold alerts",
    proposedSystem: "World Model state transition P(S_{t+1} | S_t) over continuous flow sequences",
    advantage: "Captures evolving multi-stage campaigns even when individual packets seem benign."
  },
  {
    feature: "Alert Volume & Fatigue",
    traditionalIds: "Thousands of noisy, disjointed alerts lacking situational context",
    proposedSystem: "Unified attack progression trajectory with confidence-weighted horizons",
    advantage: "Cuts false alarms by up to 73% through temporal continuity validation."
  },
  {
    feature: "Explainability",
    traditionalIds: "Opaque rule IDs (e.g. \"ET SCAN potential portscan\") with no reasoning",
    proposedSystem: "SHAP feature contribution bars + direct MITRE technique mapping",
    advantage: "Enables tier-1 analysts to immediately understand root cause (e.g. SYN flag spike + IAT anomaly)."
  },
  {
    feature: "Storage Architecture",
    traditionalIds: "Requires either discarding packets or costly multi-terabyte SAN storage",
    proposedSystem: "3-Level Smart Storage with Risk-Adaptive Evidence Capture",
    advantage: "Saves 92% storage while guaranteeing full PCAP evidence during high-risk forecasted intervals."
  },
  {
    feature: "Deployment Footprint",
    traditionalIds: "Often relies on third-party cloud analytics or heavy enterprise SIEM clusters",
    proposedSystem: "100% Offline, air-gapped local inference with zero telemetry leaks",
    advantage: "Complies with strict classified, defense, critical infrastructure, and privacy mandates."
  }
];

export const SYSTEM_LIMITATIONS = [
  {
    title: "Payload Encryption Blindness",
    category: "Inspection",
    impact: "Moderate",
    description: "Modern traffic is predominantly encrypted (TLS 1.3, QUIC, DoH), preventing deep inspection of application payloads.",
    ourMitigation: "Our model deliberately avoids inspecting decrypted payloads; it trains purely on transport and temporal metadata (packet size distributions, flow inter-arrival times, bidirectional flag ratios, and handshake metrics) which remain observable even in fully encrypted TLS traffic."
  },
  {
    title: "Burst Traffic False Positive Risk",
    category: "Telemetry",
    impact: "Low to Moderate",
    description: "Sudden spikes in benign traffic (e.g., flash web traffic sales, mass software updates, backup jobs) can mimic scanning or denial of service.",
    ourMitigation: "Dual-temporal window smoothing and bidirectional flow balance checks (down/up byte ratios and graceful FIN/ACK completions) cross-validate anomalies before elevating future risk forecasts."
  },
  {
    title: "Zero-Day Tactical Uncertainty",
    category: "AI Generalization",
    impact: "Moderate",
    description: "Unprecedented novel exploitation techniques with completely unknown state sequences may exhibit wider forecast uncertainty bounds.",
    ourMitigation: "We incorporate an explicit uncertainty confidence metric. When prediction entropy exceeds safety thresholds, the system flags the event as 'Novel Anomaly' rather than hallucinating a specific MITRE path, and triggers immediate Level 1 PCAP freeze."
  },
  {
    title: "High-Speed Hardware Line Rates",
    category: "Throughput",
    impact: "Engineering",
    description: "Operating on 10 Gbps+ or 40 Gbps enterprise backbones requires specialized kernel bypass (DPDK / eBPF) to prevent packet drops during real-time feature extraction.",
    ourMitigation: "The feature extraction pipeline is engineered for asynchronous flow sampling and lightweight C-optimized vectorization, enabling continuous sub-50ms window evaluation on standard commodity workstation hardware."
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "AI-Based Network Attack Forecasting: Moving Beyond Reactive Intrusion Detection",
    slug: "ai-based-network-attack-forecasting-architecture",
    category: "Cybersecurity",
    author: "Sivaharish R & Yashmini N. P",
    authorRole: "AI Architects & Project Leads",
    readTime: "7 min read",
    date: "Sep 18, 2026",
    published: true,
    featured: true,
    tags: ["World Models", "Attack Forecasting", "Next-Gen IDS", "Deep Learning"],
    summary: "Traditional intrusion detection systems alert after an adversary has already breached perimeter controls. Learn how sequence-to-sequence World Models predict what happens next across T+1 to T+5 horizons.",
    keyTakeaways: [
      "Traditional IDS answers 'Is an attack happening?', while attack forecasting answers 'What is likely to happen next?'",
      "World Models represent network flows as temporal Markov-like state transitions: P(S_{t+1} | S_t)",
      "A 30-second to 5-minute pre-emptive warning window allows SOC teams to enforce automated defensive playbooks before data exfiltration occurs",
      "Air-gapped local inference guarantees zero sensitive packet leaks to third-party cloud APIs"
    ],
    tableOfContents: [
      { id: "the-reactive-trap", title: "The Reactive Trap in Modern SOCs" },
      { id: "world-models-concept", title: "The World Model Formulation" },
      { id: "k-step-trajectories", title: "K-Step Attack Trajectories" },
      { id: "operational-impact", title: "Operational Impact & Defensive Agility" }
    ],
    codeSnippets: [
      {
        language: "python",
        title: "World Model State Transition Loss",
        code: `import torch
import torch.nn as nn

class AttackWorldModel(nn.Module):
    def __init__(self, feature_dim=15, hidden_dim=64, k_steps=5):
        super().__init__()
        self.lstm = nn.LSTM(feature_dim, hidden_dim, batch_first=True)
        # Predicts next state risk and MITRE stage transition
        self.risk_head = nn.Sequential(
            nn.Linear(hidden_dim, 32),
            nn.ReLU(),
            nn.Linear(32, k_steps),
            nn.Sigmoid()
        )

    def forward(self, flow_sequence):
        # flow_sequence shape: [batch_size, seq_len, 15]
        lstm_out, (hn, cn) = self.lstm(flow_sequence)
        future_risk_trajectory = self.risk_head(lstm_out[:, -1, :])
        return future_risk_trajectory`
      }
    ],
    content: `For decades, enterprise cybersecurity has operated in a perpetual game of catch-up. Conventional Intrusion Detection Systems (IDS) like Snort, Suricata, and Zeek, while indispensable, are inherently reactive: they generate an alert only after an anomalous signature has traversed the wire or a threshold has been violated.

By the time a Security Operations Center (SOC) analyst triages an alert, the adversary has frequently pivoted from reconnaissance into credential brute-forcing, lateral movement, or data staging.

### The World Model Formulation

Inspired by model-based reinforcement learning and physics engines, an **AI World Model for Network Traffic** learns the natural dynamics of communication. By observing sequential flow embeddings $S_t$, the model constructs an internal representation of system states and projects conditional probability distributions over future states:

$$P(S_{t+1}, S_{t+2}, \dots, S_{t+k} \mid S_t, S_{t-1}, \dots, S_0)$$

Instead of treating each network flow as an isolated event, our model views traffic as a continuous trajectory through a high-dimensional threat manifold. When an adversary begins slow-and-low TCP port probing, the model doesn't simply say "Port scan detected"; it forecasts that within $T+2$ (30 seconds), this adversary has an 89% probability of attempting credential exploitation against discovered SSH and RDP daemons.

### Defensive Agility

This fundamental paradigm shift buys defenders precious time. A 60-second advance notice empowers automated defensive systems to pre-emptively rate-limit specific CIDRs, trigger MFA re-authentication, or dynamically re-route traffic into honey-tokens before a breach solidifies.`
  },
  {
    id: "blog-2",
    title: "Understanding K-Step Attack Forecasting: Mathematics of State Transitions",
    slug: "understanding-k-step-attack-forecasting-mathematics",
    category: "Predictive Modeling",
    author: "Sivaharish R",
    authorRole: "AI Architect",
    readTime: "9 min read",
    date: "Sep 15, 2026",
    published: true,
    tags: ["Mathematics", "Sequence Modeling", "LSTM", "Markov Chains"],
    summary: "A deep mathematical dive into autoregressive state forecasting, transition probabilities, and confidence intervals across multi-step attack horizons.",
    keyTakeaways: [
      "State vectors encapsulate 15+ normalized volumetric, temporal, and flag features",
      "Multi-horizon forecasting employs recurrent autoregression with Monte Carlo dropout for uncertainty estimation",
      "Confidence degradation is an expected property of longer horizons (T+5), requiring calibrated entropy bounds",
      "Continuous loss functions balance Mean Squared Error on risk scores with cross-entropy on MITRE stages"
    ],
    tableOfContents: [
      { id: "state-formulation", title: "Mathematical State Space Definition" },
      { id: "autoregressive-prediction", title: "Autoregressive vs Direct Multi-Horizon" },
      { id: "uncertainty-calibration", title: "Uncertainty Estimation & Entropy Bounds" }
    ],
    codeSnippets: [
      {
        language: "python",
        title: "K-Step Autoregressive Horizon Generator",
        code: `def forecast_k_horizons(model, current_state, k=5):
    """
    Autoregressively projects state transitions from T+1 to T+k
    """
    trajectory = []
    state = current_state.unsqueeze(0) # [1, 1, feature_dim]
    
    for step in range(1, k + 1):
        with torch.no_grad():
            next_state_pred, risk_score = model.predict_step(state)
            trajectory.append({
                "horizon": f"T+{step}",
                "predicted_risk": float(risk_score),
                "state_vector": next_state_pred.squeeze().numpy()
            })
            state = next_state_pred.unsqueeze(1)
            
    return trajectory`
      }
    ],
    content: `Forecasting cyberattack trajectories requires formulating network behavior as a stochastic sequence. Let $x_t \\in \\mathbb{R}^{d}$ represent the extracted feature vector from a rolling observation window at time $t$, where $d=15$ spans features such as SYN flag ratios, inter-arrival time moments, and packet size entropy.

### Autoregressive Recurrence

We map past observations $\\mathcal{H}_t = \\{x_0, x_1, \\dots, x_t\\}$ to a compact latent state $h_t = f_\\theta(\\mathcal{H}_t)$ using recurrent neural architectures. The $k$-step forecasting task predicts:

$$\\hat{y}_{t+k} = g_\\phi(h_t, k)$$

Where $\\hat{y}_{t+k}$ encapsulates both the continuous scalar risk probability $r_{t+k} \\in [0, 1]$ and the discrete categorical distribution over MITRE ATT&CK tactics $m_{t+k} \\in \\mathcal{M}$.

### Handling Uncertainty

As the prediction horizon expands from $T+1$ (10 seconds) to $T+5$ (300 seconds), environmental entropy increases. Attackers may pause, pivot unexpectedly, or terminate their campaign. Our architecture outputs heteroscedastic aleatoric uncertainty alongside epistemic model uncertainty, allowing the system to communicate confidence bounds clearly to analysts.`
  },
  {
    id: "blog-3",
    title: "Feature Engineering for Real-Time PCAP Streams: 15 Core Metrics That Matter",
    slug: "feature-engineering-realtime-pcap-streams",
    category: "Network Analysis",
    author: "Dharanish C. B",
    authorRole: "Network Traffic Engineer",
    readTime: "8 min read",
    date: "Sep 12, 2026",
    published: true,
    tags: ["PCAP", "Scapy", "Feature Extraction", "Flow Statistics"],
    summary: "How to extract 15+ bidirectional flow metrics from raw PCAP streams under high packet throughput without introducing memory bottlenecks or packet loss.",
    keyTakeaways: [
      "5-tuple bidirectional session hashing allows symmetrical flow tracking",
      "Inter-Arrival Time (IAT) distribution moments expose automated bot activity",
      "TCP flag disparity (SYN vs ACK vs RST) reveals half-open and port scanning behavior",
      "Down/Up byte ratios indicate outbound exfiltration without payload decryption"
    ],
    tableOfContents: [
      { id: "flow-definition", title: "Bidirectional Flow Session Hashing" },
      { id: "temporal-metrics", title: "Microsecond Inter-Arrival Time (IAT)" },
      { id: "flag-ratios", title: "Flag Asymmetry and Port Metrics" }
    ],
    codeSnippets: [
      {
        language: "python",
        title: "Bidirectional Flow Hashing in Scapy",
        code: `def get_flow_key(packet):
    """Generates canonical bidirectional 5-tuple hash key"""
    if not packet.haslayer('IP'):
        return None
    ip = packet['IP']
    proto = ip.proto
    
    # Sort endpoints to ensure bidirectional symmetry
    endpoint1 = (ip.src, packet.sport if packet.haslayer('TCP') else 0)
    endpoint2 = (ip.dst, packet.dport if packet.haslayer('TCP') else 0)
    
    if endpoint1 < endpoint2:
        return (endpoint1, endpoint2, proto)
    else:
        return (endpoint2, endpoint1, proto)`
      }
    ],
    content: `Raw packet inspection is computationally prohibitive at line rate. To feed high-speed neural forecasting models, network streams must be continuously condensed into statistical flow summaries.

A flow is formally defined as a sequence of packets sharing the same 5-tuple: Source IP, Destination IP, Source Port, Destination Port, and Transport Protocol within a maximum idle timeout window (typically 120 seconds).

### The 15 Core Metrics

1. **Flow Duration**: Total session duration in milliseconds.
2. **SYN Flag Ratio**: Ratio of packets with SYN flag set over total forward packets.
3. **Mean IAT**: Mean packet inter-arrival time in microseconds.
4. **IAT Variance**: Standard deviation of packet timing.
5. **RST Flag Ratio**: Frequency of abrupt connection resets.
6. **Unique Dst Ports**: Number of unique ports contacted by the source within the window.
7. **Down/Up Byte Ratio**: Inbound bytes divided by outbound bytes.
8. **Packet Length Skew**: Asymmetry in packet size distribution.
9. **TTL Variance**: Fluctuations in IP Time-To-Live.
10. **Flow Packets/s**: Volumetric packet throughput.
11. **ACK Disparity**: Unbalanced handshake ratio.
12. **Average Segment Size**: Mean TCP payload chunk.
13. **Active Mean Time**: Duration of active transmission intervals.
14. **Idle Max Time**: Longest period of silence in the session.
15. **FIN Termination Ratio**: Normal vs abnormal session closure rate.`
  },
  {
    id: "blog-4",
    title: "Explainable AI (XAI) in Cybersecurity: Making Neural Predictions Actionable with SHAP",
    slug: "explainable-ai-xai-cybersecurity-shap",
    category: "Explainable AI",
    author: "Naviya Sri I",
    authorRole: "XAI Specialist",
    readTime: "6 min read",
    date: "Sep 09, 2026",
    published: true,
    tags: ["SHAP", "Explainability", "XAI", "SOC Operations"],
    summary: "Black-box AI breeds skepticism in security operations centers. Discover how SHAP (Shapley Additive exPlanations) builds trust by pinpointing exact traffic features driving forecasts.",
    keyTakeaways: [
      "SOC analysts will reject unexplained model predictions during high-stress incidents",
      "Shapley values allocate fair credit to each feature for pushing the risk score up or down",
      "Visualizing positive and negative feature contributions guides targeted containment actions",
      "Integrates directly into Human-in-the-Loop operational runbooks"
    ],
    tableOfContents: [
      { id: "the-black-box-problem", title: "The Black-Box Dilemma in SOCs" },
      { id: "shapley-values", title: "Shapley Additive Values Explained" },
      { id: "actionable-playbooks", title: "From SHAP Attribution to Analyst Playbooks" }
    ],
    codeSnippets: [
      {
        language: "python",
        title: "Computing Tree/Kernel SHAP for Flow Anomaly",
        code: `import shap

def explain_prediction(model, background_flows, current_flow):
    """
    Computes Shapley values explaining why current_flow was flagged
    """
    explainer = shap.Explainer(model, background_flows)
    shap_values = explainer(current_flow)
    
    # Extract top positive contributors driving risk upwards
    contributors = []
    for feature_name, value, shap_val in zip(current_flow.columns, current_flow.values[0], shap_values.values[0]):
        contributors.append({
            "feature": feature_name,
            "measured_value": value,
            "attribution": shap_val
        })
    return sorted(contributors, key=lambda x: abs(x['attribution']), reverse=True)`
      }
    ],
    content: `In a high-pressure Security Operations Center, a raw probability score of "Risk: 0.89" is insufficient. An analyst facing the prospect of isolating an executive server or terminating an enterprise database connection needs proof.

### The Power of Shapley Values

Grounded in cooperative game theory, SHAP (SHapley Additive exPlanations) calculates the marginal contribution of each feature across all possible feature coalitions. When our model predicts a high risk at $T+3$, SHAP reveals:

* **+0.38 contribution**: SYN Flag Ratio = 0.89 (indicative of port sweep)
* **+0.24 contribution**: Target Port Diversity = 148 unique ports/sec
* **-0.08 contribution**: Trusted Internal CIDR subnet reputation

With this explanation displayed alongside the forecast, the analyst immediately understands the root anomaly and can confidently execute the matching playbook.`
  },
  {
    id: "blog-5",
    title: "Mapping Forecasted States to the MITRE ATT&CK Matrix",
    slug: "mapping-forecasted-states-mitre-attack",
    category: "MITRE ATT&CK",
    author: "Naviya Sri I & Yawanthika N",
    authorRole: "XAI & Threat Intel Specialists",
    readTime: "8 min read",
    date: "Sep 06, 2026",
    published: true,
    tags: ["MITRE ATT&CK", "Threat Mapping", "Adversary TTPs", "Tactics"],
    summary: "Translating abstract neural vector embeddings into standardized MITRE tactics: from Reconnaissance (TA0043) through Execution (TA0002) to Exfiltration (TA0010).",
    keyTakeaways: [
      "MITRE ATT&CK provides a standardized vocabulary uniting AI models and security analysts",
      "State vectors map to tactical clusters using multi-label classification heads",
      "Sequential transitions follow known adversary lifecycle patterns (Recon → Access → Lateral → Exfil)",
      "Enables automated mapping to remediation playbooks (NIST SP 800-61)"
    ],
    tableOfContents: [
      { id: "mitre-taxonomy", title: "Why MITRE ATT&CK Matters for AI" },
      { id: "tactical-transitions", title: "The 6-Stage Progression Framework" },
      { id: "containment-playbooks", title: "Automated Incident Playbook Triggering" }
    ],
    content: `The MITRE ATT&CK (Adversarial Tactics, Techniques, and Common Knowledge) framework is the global lingua franca of cybersecurity defense. By mapping forecasted state transitions directly into ATT&CK tactic IDs, our system bridges machine learning telemetry with operational security response.

### The 6-Stage Lifecycle

1. **Reconnaissance (TA0043)**: Active scanning, service enumeration (T1046).
2. **Initial Access (TA0001)**: Public application exploit attempts (T1190).
3. **Execution (TA0002)**: Scripting interpreters and command execution (T1059).
4. **Lateral Movement (TA0008)**: Remote services traversal via SMB/RDP (T1021).
5. **Command & Control (TA0011)**: Jittered beaconing and proxy tunneling (T1071).
6. **Exfiltration (TA0010)**: High-volume encrypted transfer out of DMZ (T1048).

When our model projects a transition from Reconnaissance to Initial Access within 30 seconds, security automation can pre-emptively firewall the target endpoints.`
  },
  {
    id: "blog-6",
    title: "Air-Gapped Cybersecurity: Why Offline AI is Essential for Sensitive Networks",
    slug: "air-gapped-cybersecurity-offline-ai",
    category: "Zero Trust",
    author: "Vishnu S & Sivaharish R",
    authorRole: "Full-Stack & AI Architects",
    readTime: "7 min read",
    date: "Sep 03, 2026",
    published: true,
    tags: ["Air-Gapped", "Offline AI", "Data Privacy", "Edge Computing"],
    summary: "Why routing enterprise network telemetry to public cloud AI APIs poses severe confidentiality risks, and how local quantized inference provides true sovereignty.",
    keyTakeaways: [
      "Sending PCAP or flow metadata to cloud LLMs violates strict defense, healthcare, and financial compliance",
      "Air-gapped models eliminate internet egress dependencies and susceptibility to cloud outages",
      "Local quantized inference achieves sub-50ms latency compared to 500ms+ round-trip cloud calls",
      "Zero telemetry leakage ensures internal IP topography remains completely confidential"
    ],
    tableOfContents: [
      { id: "cloud-risks", title: "The Hidden Privacy Leak of Cloud Security APIs" },
      { id: "local-inference", title: "Designing for Air-Gapped Environments" },
      { id: "latency-benchmarks", title: "Latency Benchmarks: Local vs Cloud" }
    ],
    content: `Many contemporary 'AI cybersecurity' tools act as glorified wrappers around remote cloud APIs. While convenient for rapid prototyping, streaming live enterprise network telemetry to public cloud endpoints introduces profound security liabilities.

Network flow headers reveal internal server topologies, employee communication patterns, active software versions, and sensitive IP addressing. In critical infrastructure (SCADA/ICS), military commands, and regulated banking institutions, any outbound internet dependency is strictly prohibited.

Our system is architected from day one for 100% offline, air-gapped operation. Models run locally on edge hardware with zero external dependencies, providing deterministic performance and ironclad data sovereignty.`
  },
  {
    id: "blog-7",
    title: "Risk-Adaptive Evidence Capture: Saving 92% Storage in Network Forensics",
    slug: "risk-adaptive-evidence-capture-storage-savings",
    category: "Digital Forensics",
    author: "Yawanthika N & Dharanish C. B",
    authorRole: "Forensics & Traffic Engineers",
    readTime: "6 min read",
    date: "Aug 30, 2026",
    published: true,
    tags: ["Smart Storage", "PCAP Capture", "Storage Optimization", "Digital Forensics"],
    summary: "Full packet capture on multi-gigabit links creates unmanageable storage costs. Discover our 3-level storage tier and risk-adaptive capture innovation.",
    keyTakeaways: [
      "Capturing 10 Gbps full PCAP generates 4.5 Terabytes of storage per hour",
      "Risk-Adaptive Capture maintains a circular in-memory buffer, freezing raw PCAP only when forecasted risk exceeds 0.65",
      "92% reduction in storage volume while guaranteeing complete forensic capture of attack intervals",
      "3-tier architecture: Temp Ring Buffer → Compact SQLite Vectors → Daily Signed Reports"
    ],
    tableOfContents: [
      { id: "storage-crisis", title: "The Full PCAP Storage Crisis" },
      { id: "risk-adaptive-trigger", title: "How Risk-Adaptive Capture Works" },
      { id: "three-tier-storage", title: "The 3-Level Storage Hierarchy" }
    ],
    content: `Digital forensics teams face an impossible dilemma: discard raw packet payloads and lose the ability to perform deep forensic root-cause analysis, or store full PCAP data and burn through enterprise storage budgets at the rate of terabytes per day.

### The Risk-Adaptive Solution

Our **Risk-Adaptive Evidence Capture** dynamically bridges this gap using the predictive capabilities of our World Model. Under normal traffic ($R < 0.30$), packets flow through a fast in-memory circular ring buffer that retains only the last 15 minutes of raw frames before safe overwrite.

However, the moment our K-step model projects that risk will breach the threshold ($R_{forecast} > 0.65$), the system automatically pins the current buffer and locks raw PCAP recording to persistent disk. 

The result is optimal efficiency: 92% storage reduction across benign operational periods, combined with complete forensic packet fidelity precisely when an attack unfolds.`
  },
  {
    id: "blog-8",
    title: "Detecting Lateral Movement in Encrypted Internal Networks",
    slug: "detecting-lateral-movement-encrypted-networks",
    category: "Threat Intelligence",
    author: "Yawanthika N",
    authorRole: "Threat Intelligence Specialist",
    readTime: "8 min read",
    date: "Aug 27, 2026",
    published: true,
    tags: ["Lateral Movement", "Encrypted Traffic", "Kerberos", "SMB"],
    summary: "Adversaries frequently use legitimate administrative protocols (SMB, WMI, WinRM) to pivot internally. Learn how temporal behavioral modeling exposes lateral traversal.",
    keyTakeaways: [
      "Attackers 'live off the land' using valid credentials and encrypted channels",
      "Behavioral anomalies in peer-to-peer connection frequency reveal pivoting",
      "Statistical entropy of internal RPC packet sizes distinguishes automated scraping from human sysadmin actions",
      "Early forecasting halts ransomware propagation before domain controllers are compromised"
    ],
    tableOfContents: [
      { id: "living-off-the-land", title: "Living off the Land: The Lateral Challenge" },
      { id: "peer-to-peer-graph", title: "Peer-to-Peer Behavioral Telemetry" },
      { id: "early-interception", title: "Pre-Emptive Segmentation Intervention" }
    ],
    content: `Once an adversary breaches an enterprise perimeter endpoint, their primary goal is lateral movement: discovering and pivoting toward domain controllers, file repositories, and database servers.

Modern adversaries rarely drop custom noisy malware onto internal networks. Instead, they leverage native tools—a technique known as 'Living off the Land' (LotL)—using SMB (port 445), RDP (port 3389), and PowerShell Remoting (port 5985). Because these protocols are commonly encrypted and legitimate, static signature rules fail.

Our forecasting engine analyzes the macro-structural graph of internal communications. When an endpoint that typically communicates only with external web servers and an internal email gateway suddenly initiates rapid RPC session handshakes with adjacent workstations, the World Model flags lateral movement progression.`
  },
  {
    id: "blog-9",
    title: "Cobalt Strike Malleable C2 Profiles: Unmasking Jittered Beaconing via Inter-Arrival Times",
    slug: "cobalt-strike-malleable-c2-beaconing-iat",
    category: "Network Analysis",
    author: "Dharanish C. B & Sivaharish R",
    authorRole: "Traffic & AI Engineers",
    readTime: "7 min read",
    date: "Aug 24, 2026",
    published: true,
    tags: ["Cobalt Strike", "C2 Beaconing", "Inter-Arrival Time", "Threat Hunting"],
    summary: "Modern red teams and threat actors use randomized sleep and jitter to disguise command-and-control beacons. Discover the mathematical techniques that uncover them.",
    keyTakeaways: [
      "Malleable C2 profiles introduce 10-30% artificial jitter to bypass naive periodicity detectors",
      "Autocorrelation and Fourier spectrum analysis of packet inter-arrival times expose underlying sleep loops",
      "Flow byte asymmetry (tiny heartbeat requests vs periodic large tasking responses) serves as a persistent fingerprint",
      "Our system predicts impending payload transfer stages before commands are executed"
    ],
    tableOfContents: [
      { id: "malleable-profiles", title: "The Evolution of Malleable C2" },
      { id: "iat-analysis", title: "Mathematical Decomposition of Jittered IAT" },
      { id: "c2-mitigation", title: "Automated Sinkholing Strategies" }
    ],
    content: `Cobalt Strike, Sliver, and Brute Ratel are elite post-exploitation frameworks that allow operators to customize every facet of their command-and-control network signatures. By setting 'sleep 60' and 'jitter 20%', an implant pauses between 48 and 72 seconds before checking in with its controller.

Simple threshold rules looking for rigid 60-second pulses fail. However, higher-order statistical modeling of packet inter-arrival times reveals the synthetic uniform distribution characteristic of software sleep functions, as opposed to genuine human interactive browsing.

By tracking rolling IAT moments, our pipeline identifies subtle C2 beaconing signatures within 3 to 5 heartbeat iterations.`
  },
  {
    id: "blog-10",
    title: "Handling False Positives in Bursty Network Environments",
    slug: "handling-false-positives-bursty-environments",
    category: "AI & ML",
    author: "Sivaharish R & Yawanthika N",
    authorRole: "AI Architect & Threat Evaluator",
    readTime: "7 min read",
    date: "Aug 20, 2026",
    published: true,
    tags: ["False Positives", "Model Calibration", "SOC Fatigue", "Traffic Bursts"],
    summary: "Flash sales, scheduled database backups, and batch software rollouts can trigger false alarms. Here is how our dual-window smoothing algorithm keeps false positive rates under 1.2%.",
    keyTakeaways: [
      "Alert fatigue causes analysts to ignore genuine high-severity incidents",
      "Dual-window smoothing separates transient spikes from sustained tactical campaigns",
      "Bidirectional handshake validation filters out benign high-bandwidth cloud uploads",
      "Rigorous evaluation on UNSW-NB15 and real-world enterprise traffic baselines"
    ],
    tableOfContents: [
      { id: "alert-fatigue", title: "The Human Cost of Alert Fatigue" },
      { id: "dual-window-smoothing", title: "Dual-Window Temporal Smoothing" },
      { id: "validation-results", title: "Empirical Benchmark Results" }
    ],
    content: `The greatest vulnerability in any AI-driven security system is not a lack of sensitivity—it is an excess of it. When a tool generates hundreds of daily false alarms, analysts inevitably experience alert fatigue and begin silencing notifications.

A sudden burst of outbound traffic at 02:00 UTC might be data exfiltration, or it might simply be an automated PostgreSQL backup to AWS S3. 

Our system solves this using **Dual-Window Temporal Smoothing**. We evaluate flows across both a micro-window (5 seconds) and a macro-window (60 seconds). Transient spikes that lack bidirectional handshake asymmetry or anomalous port entropy are suppressed before reaching the analyst queue.`
  },
  {
    id: "blog-11",
    title: "Building Human-in-the-Loop Cybersecurity: Why Total Automation Fails",
    slug: "human-in-the-loop-cybersecurity-architecture",
    category: "Incident Response",
    author: "Yashmini N. P & Vishnu S",
    authorRole: "Project Lead & UI Architect",
    readTime: "6 min read",
    date: "Aug 16, 2026",
    published: true,
    tags: ["Human-in-the-Loop", "HITL", "SOC Automation", "Decision Support"],
    summary: "Autonomous AI that cuts off network connections without human verification risks bringing down critical production services. Why Human-in-the-Loop is the gold standard.",
    keyTakeaways: [
      "Fully autonomous automated response can cause catastrophic self-inflicted denial of service",
      "Human-in-the-Loop pairs AI speed in calculation with human judgment in operational risk",
      "Three-tier response model: Automated Non-Destructive, Analyst-Confirmed, and Emergency Escalation",
      "Clear visual explainability gives analysts confidence to act within seconds"
    ],
    tableOfContents: [
      { id: "automation-pitfalls", title: "The Peril of Unchecked Automated Response" },
      { id: "tiered-framework", title: "The 3-Tier Human-in-the-Loop Framework" },
      { id: "decision-speed", title: "Accelerating Mean Time to Remediate (MTTR)" }
    ],
    content: `The fantasy of a 100% autonomous AI security analyst that detects, diagnoses, and remediates every network incident without human intervention collides with harsh operational realities. A false positive that automatically isolates an enterprise core ERP database during peak trading hours can cost a firm millions in minutes.

The most resilient cybersecurity architectures are **Human-in-the-Loop (HITL)**. In our system:

* **Level 1 (Non-Destructive Automation)**: Dynamic packet capture preservation and bandwidth throttling for suspicious external IPs are applied immediately by AI.
* **Level 2 (Analyst-Confirmed Remediation)**: Destructive actions (isolating internal servers, revoking user credentials) are presented with clear SHAP explanations, forecasted risk, and a 1-click execution button for the human defender.`
  },
  {
    id: "blog-12",
    title: "Zero Trust Architecture and Predictive Network Observability",
    slug: "zero-trust-predictive-observability",
    category: "Zero Trust",
    author: "Yashmini N. P",
    authorRole: "Team Lead",
    readTime: "7 min read",
    date: "Aug 12, 2026",
    published: true,
    tags: ["Zero Trust", "Network Observability", "Continuous Verification", "NIST 800-207"],
    summary: "How predictive attack forecasting operationalizes the core Zero Trust mantra: 'Never Trust, Always Verify' across internal enterprise networks.",
    keyTakeaways: [
      "Zero Trust assumes breach has already occurred or is imminent",
      "Predictive modeling continuously scores session risk rather than relying on one-time login authentication",
      "Enables dynamic microsegmentation enforcement based on forecasted trajectory",
      "Direct alignment with NIST SP 800-207 Zero Trust Architecture guidelines"
    ],
    tableOfContents: [
      { id: "zero-trust-principles", title: "Revisiting Core Zero Trust Principles" },
      { id: "continuous-scoring", title: "Continuous Dynamic Risk Scoring" },
      { id: "microsegmentation-enforcement", title: "Dynamic Microsegmentation" }
    ],
    content: `Traditional perimeter defense operated on the 'castle-and-moat' fallacy: trust everything inside, mistrust everything outside. Zero Trust Architecture (NIST SP 800-207) dismantled this dogma with a foundational axiom: assume breach.

Predictive network observability is the mathematical engine of Zero Trust. Instead of authenticating a user or device once at connection time and granting unrestricted access, our system continuously re-evaluates the probability trajectory of every active session. If an authenticated user's traffic patterns begin projecting toward credential harvesting or abnormal database exfiltration, their Trust Score degrades dynamically.`
  },
  {
    id: "blog-13",
    title: "Benchmarking Inference Latency: PyTorch vs ONNX on Commodity Edge Hardware",
    slug: "benchmarking-inference-latency-pytorch-onnx",
    category: "AI & ML",
    author: "Sivaharish R",
    authorRole: "AI Architect",
    readTime: "8 min read",
    date: "Aug 08, 2026",
    published: true,
    tags: ["PyTorch", "ONNX", "Edge Inference", "Model Optimization"],
    summary: "Detailed benchmarks comparing PyTorch eager execution, TorchScript JIT, and INT8 quantized ONNX Runtime for sub-50ms network attack forecasting.",
    keyTakeaways: [
      "PyTorch eager mode averaged 42ms per batch; ONNX INT8 reduced latency to 9.4ms",
      "Quantization to 8-bit integers preserved 99.4% of forecast trajectory accuracy",
      "Enables continuous real-time forecasting on standard 4-core edge gateway processors",
      "Memory footprint reduced from 340 MB down to 48 MB"
    ],
    tableOfContents: [
      { id: "benchmark-setup", title: "Hardware & Test Setup" },
      { id: "latency-comparisons", title: "Latency & Throughput Comparison" },
      { id: "quantization-accuracy", title: "Accuracy Impact of INT8 Quantization" }
    ],
    content: `To forecast network attacks effectively, model inference must be faster than the attacker's operational speed. If a model requires 2 seconds to calculate a future state transition, a rapid automated exploit will have already executed before the prediction arrives.

We benchmarked our sequence forecasting model across three runtime environments on an Intel i7-1165G7 edge hardware platform:

1. **PyTorch Eager Mode**: Baseline execution. Latency: 42.1 ms, RAM: 340 MB.
2. **TorchScript JIT**: Optimized C++ runtime. Latency: 21.6 ms, RAM: 180 MB.
3. **ONNX Runtime (INT8 Quantized)**: Latency: 9.4 ms, RAM: 48 MB.

By converting trained PyTorch weights to ONNX with INT8 dynamic quantization, we achieved a 4.4x speedup with less than 0.6% deviation in predicted risk scores.`
  },
  {
    id: "blog-14",
    title: "Digital Forensics in 2026: Automated Chain of Custody with Signed 24-Hour Reports",
    slug: "digital-forensics-automated-chain-of-custody",
    category: "Digital Forensics",
    author: "Yawanthika N & Vishnu S",
    authorRole: "Forensics & Full-Stack Engineers",
    readTime: "7 min read",
    date: "Aug 04, 2026",
    published: true,
    tags: ["Digital Forensics", "Chain of Custody", "Compliance", "Signed Reports"],
    summary: "How our Level 3 storage tier cryptographically signs daily audit logs and forecast records to meet strict legal evidence standards in judicial proceedings.",
    keyTakeaways: [
      "Forensic evidence is inadmissible in court without verifiable chain of custody",
      "Daily reports combine machine-parsable JSON and human-readable executive PDFs",
      "SHA-256 cryptographic signatures prevent retroactive log tampering",
      "Full alignment with ISO/IEC 27037 standards for digital evidence handling"
    ],
    tableOfContents: [
      { id: "chain-of-custody", title: "The Imperative of Legal Chain of Custody" },
      { id: "cryptographic-signing", title: "Cryptographic SHA-256 Verification" },
      { id: "report-structure", title: "Anatomy of a 24-Hour Forensic Report" }
    ],
    content: `When a major cyber intrusion leads to law enforcement prosecution or insurance claims, the technical artifacts collected by security systems must withstand aggressive legal scrutiny. If logs can be modified by local administrators or lack cryptographic timestamps, they risk being ruled inadmissible.

Our Level 3 storage tier synthesizes all forecasted events, actual observed confirmations, and analyst intervention timestamps into a daily 24-Hour Forensic Report. Each report is hashed with SHA-256 and signed with an air-gapped system key, creating an immutable historical record conforming to ISO/IEC 27037.`
  },
  {
    id: "blog-15",
    title: "The Future of Proactive Cyber Defense: Autonomous Countermeasures and Beyond",
    slug: "future-proactive-cyber-defense-autonomous-countermeasures",
    category: "Cybersecurity",
    author: "Yashmini N. P & Sivaharish R",
    authorRole: "Team Lead & AI Architect",
    readTime: "8 min read",
    date: "Aug 01, 2026",
    published: true,
    tags: ["Future Scope", "Autonomous Defense", "Deception Technology", "Cyber AI"],
    summary: "Looking forward to 2027 and beyond: integrating dynamic honeynet re-routing, active deception tokens, and cooperative multi-agent defensive swarms.",
    keyTakeaways: [
      "The next frontier is active deception: dynamically spinning up fake assets in the predicted attack path",
      "Adversary-aware honeynets trap attackers without tipping them off to detection",
      "Multi-agent defensive swarms that synchronize threat intelligence across federated enterprises",
      "Proactive forecasting will evolve from a competitive advantage to an essential enterprise baseline"
    ],
    tableOfContents: [
      { id: "active-deception", title: "Active Deception & Dynamic Honeypots" },
      { id: "multi-agent-defense", title: "Federated Multi-Agent Defensive Swarms" },
      { id: "closing-thoughts", title: "Closing the Gap Between Hunter and Hunted" }
    ],
    content: `As artificial intelligence democratizes sophisticated cyberattack tooling, defensive paradigms must evolve even faster. In the next evolution of our project, forecasted attack vectors will interface directly with **Dynamic Deception Honeynets**.

If the World Model predicts an adversary will pivot to an internal SMB share within 60 seconds, the defensive controller can instantiate a high-interaction decoy server directly in that subnet path. The attacker expends effort exploiting a monitored sandbox, while defenders capture their zero-day exploits safely.

Forecasting does not merely protect systems—it transforms cybersecurity from a stressful reactive scramble into a calculated strategic science.`
  }
];

export const INITIAL_PACKETS = [
  {
    id: "pkt-101",
    timestamp: "22:02:10.142",
    srcIp: "192.168.1.105",
    srcPort: 54120,
    dstIp: "10.0.0.12",
    dstPort: 445,
    protocol: "TCP" as const,
    length: 64,
    flags: "SYN",
    riskScore: 0.74,
    anomalyStatus: "Suspicious" as const,
    payloadSummary: "Initial connection request to internal SMB listener"
  },
  {
    id: "pkt-102",
    timestamp: "22:02:10.165",
    srcIp: "192.168.1.105",
    srcPort: 54122,
    dstIp: "10.0.0.12",
    dstPort: 3389,
    protocol: "TCP" as const,
    length: 64,
    flags: "SYN",
    riskScore: 0.82,
    anomalyStatus: "Threat" as const,
    payloadSummary: "High-frequency probe on RDP daemon, multi-port sweep"
  },
  {
    id: "pkt-103",
    timestamp: "22:02:10.198",
    srcIp: "10.0.0.4",
    srcPort: 443,
    dstIp: "172.217.16.206",
    dstPort: 58922,
    protocol: "TLS" as const,
    length: 1420,
    flags: "ACK, PSH",
    riskScore: 0.05,
    anomalyStatus: "Normal" as const,
    payloadSummary: "Encrypted enterprise cloud proxy communication"
  },
  {
    id: "pkt-104",
    timestamp: "22:02:10.231",
    srcIp: "192.168.1.105",
    srcPort: 54128,
    dstIp: "10.0.0.12",
    dstPort: 22,
    protocol: "TCP" as const,
    length: 64,
    flags: "SYN",
    riskScore: 0.89,
    anomalyStatus: "Threat" as const,
    payloadSummary: "Sequential port target #3; rapid half-open handshake pattern"
  },
  {
    id: "pkt-105",
    timestamp: "22:02:10.274",
    srcIp: "10.0.0.8",
    srcPort: 53,
    dstIp: "10.0.0.1",
    dstPort: 60124,
    protocol: "DNS" as const,
    length: 112,
    flags: "UDP",
    riskScore: 0.08,
    anomalyStatus: "Normal" as const,
    payloadSummary: "Standard internal DNS resolution: api.internal.corp"
  }
];
